### PR TITLE
The migration and member model was created

### PR DESCRIPTION
**Pull request by AlanAlexis11**
**Summary**
- Model members
   - name:string
   - image:string
- Migration
   - name:string
   - image:string
 
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT197/boards/277?modal=detail&selectedIssue=OT197-72

### CODE REVIEW

**Comment by guillote87** [comment]
Ahi revise con la info de la US, estaria ok

**Comment by guillote87** [comment]
OK

**Review by guillote87 — COMMENTED** [review]
OK

**Review by JonaPortillo — COMMENTED** [review]
OK

**Pull request closed without merging**
